### ISSUE TITLE
iOS SDK setCustomDimensionForID not documented

### ISSUE THREAD

**Issue by aeirola** [PiwikPRO/PPMS-PublicDocs#521]
Version [1.0.6](https://github.com/PiwikPRO/piwik-pro-sdk-framework-ios/compare/1.0.5...1.0.6) of the iOS SDK introduced a new method [`setCustomDimensionForID`](https://github.com/PiwikPRO/piwik-pro-sdk-framework-ios/blob/1.0.6/PiwikPROSDK.framework/Headers/PiwikTracker.h#L431) deprecating the older [`setCustomDimensionForIndex`](https://github.com/PiwikPRO/piwik-pro-sdk-framework-ios/blob/1.0.6/PiwikPROSDK.framework/Headers/PiwikTracker.h#L421). Unfortunately the new method is not documented in the official documentation https://developers.piwik.pro/en/latest/sdk/Piwik_PRO_SDK_for_iOS.html#tracking-with-custom-dimensions which still only references the now deprecated mehtod.

**Comment by harmasz** [comment]
Hello @aeirola, we took care of this issue with https://github.com/PiwikPRO/PPMS-PublicDocs/pull/777 and since version 16.8 of the documentation we are showing `setCustomDimensionForID` in the example code. We can also replace all mentions of an 'index' with an 'ID' to make it more clear.
