### ISSUE TITLE
Deprecation of JCenter on Android platform

### ISSUE THREAD

**Issue by GBenoitG** [PiwikPRO/PPMS-PublicDocs#620]
I noticed that your library is currently in the JCenter repository, but this one is now deprecated on Android with the latest Gradle version.
Is there any documentation about a migration?

**Comment by harmasz** [comment]
Hi @GBenoitG, we have just migrated our Android SDK to Jitpack: https://jitpack.io/#pro.piwik/sdk-framework-android
We will be updating the docs shortly.

**Comment by harmasz** [comment]
The docs are live: 
https://developers.piwik.pro/en/latest/data_collection/mobile/Piwik_PRO_SDK_for_Android.html#including-the-library

**Comment by GBenoitG** [comment]
Thank you, I will look into it 👍
