### ISSUE TITLE
Swift Compiler Error : Missing argument for parameter 'path' in call

### ISSUE THREAD

**Issue by NonowPoney** [PiwikPRO/PPMS-PublicDocs#951]
Hello, 

I've an issue when compiling flutter_piwikpro (1.0.0) for iOS :

Swift Compiler Error (Xcode): Missing argument for parameter 'path' in call
../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_piwikpro-1.0.0/ios/Classes/SwiftFlutterPiwikProPlugin.swift:202:87

 Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-arm, locale fr-FR)
    • Flutter version 3.3.4 on channel stable at /tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (2 weeks ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

**Comment by harmasz** [comment]
@NonowPoney the issue should be fixed with `flutter_piwikpro: ^1.0.1`
